### PR TITLE
Various usability improvements

### PR DESCRIPTION
**Pull request by cyco**
This pr introduces common keyboard shortcuts for common task (e.g. cmd + n to create a new database entry) and fixes some minor ui issues.

### CODE REVIEW

**Comment by cyco** [comment]
Do you want me to add license headers?

**Comment by melloware** [comment]
Nice work!

**Comment by mstarke** [comment]
Thanks for the contribution!

**Comment by mstarke** [comment]
What I do not like is the OpenPanel on the path control. I tried to find the menu and check what action gets invoked but I did not put that much effort into it, but I think this should be done via the menu not via the "first-responder" way. Anyway. I like what you did a lot!

**Comment by mstarke** [comment]
I cleaned up some of the code, removed the duplicate delegate creation (via code as well as xib) and I rolled back the key-path-control popup as this is rather intrusive. I found the private API ```[NSPathControlCell:_otherItemClicked:]``` that needs to be send to NSPathControlCell to get the internal behaviour. Also, I am a bit sceptical on the New-Submenu front but I keept is. Cmd+N is for new documents in my head, but this is so much less frequently used than creating new entries or group it shoud get the easies shortcut.

**Comment by cyco** [comment]
Thanks for the feedback.
I wanted to be able to easily choose a keyfile using only the keyboard, but NSPathControl can't be _activated_ using public APIs (except for the private API you mentioned). Maybe i went a little too far with the timeout and open panel :)

As for the _New_ submenu, i thought this was how the default apps did it. But now that i'm checking it it turns out to be inconsistent. Finder just lists all items, while iTunes uses a submenu. 

itunes-new

finder-new

**Pull request merged**
