### PR TITLE
Improved or added ES localisations

### PR DESCRIPTION
**Pull request by m0yP**
Even updated Credits.rtf ;)

### CODE REVIEW

**Comment by mstarke** [comment]
Awesome. I would suggest using an external XLIFF tool. I recently started using the process documented by Apple (see https://developer.apple.com/library/content/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html) and this is highly preferable. The only downside is the order of the string files get's changed to alphabetic.

**Comment by mstarke** [comment]
If you come around to export/import a XLIFF you might want to update the pull request with the additional changes.

**Comment by m0yP** [comment]
Sure! Looks way cleaner for all of us. Which editor do you suggest?

**Comment by mstarke** [comment]
I'm using a custom build of [XLIFFTool](https://itunes.apple.com/de/app/xlifftool/id1074282695?mt=12) and [iXLIFF](https://itunes.apple.com/de/app/ixliff/id944658897?mt=12) since I did not came around to add the "set target language" feature to XLIFFTool. Both of them work nice and do the job.

**Pull request merged**
