### PR TITLE
Trash folders automatically set to have autotype disabled.

### PR DESCRIPTION
**Pull request by JordanSekky**
Just two lines that provide a potential solution to #357. If the recycle bin setting is set to auto-create a trash folder, it creates it with autotype disabled. Changing the recycle bin folder also disables auto-type on the new selection.

Some things to consider: 
* Is this a sane default, or should it provide user the user with an option before it does it?
* When changing the recycle bin folder manually, should the old folder be reset back to inherit autotype settings?

### CODE REVIEW

**Comment by mstarke** [comment]
I thinks it's bad to actually change the attributes in the group. It's a semantic that is provided by the setting as a trash folder. I'd go another way and judge exclude the trash while collections entries and groups for auto type or search. Don't get me wrong. I like that you try to contribute but I think this not the best approach.

**Comment by mstarke** [comment]
The place that makes more sense to me should be in KPKGroup

````
- (NSArray *)searchableChildEntries;
````

**Comment by mstarke** [comment]
And

````
- (NSArray *)autotypeableChildEntries;
````

**Comment by JordanSekky** [comment]
Okay, I totally agree that is a much better and more reasonable way to do it. New pull request submitted in KeePassKit's repository.

**Pull request closed without merging**
