### PR TITLE
Solved the problem: crashing on closing preview no mac-sierra

### PR DESCRIPTION
**Pull request by rdoering**

### CODE REVIEW

**Comment by mstarke** [comment]
Could you exchange the pull request to fall back to a simple delete that way it fixes the crash and I can merge the pull request.

The main problem is exactly as you describe and that's why the warning is next to the "enable quicklook" setting. I did not investigate any further who to use in memory files for quick look. A quick search yielded this however: http://stackoverflow.com/questions/8917368/display-encrypted-file-using-quicklook-framework-or-uidocumentinteractioncontrol which might be a feasable solution although an ugly one.

**Comment by rdoering** [comment]
I will. I just wanted you to know that it is in progress.

**Comment by Jellyfrog** [comment]
use `rm -P` instead?
>  -P          Overwrite regular files before deleting them.  Files are overwritten three times, first with the byte pattern 0xff, then 0x00, and then 0xff again, before they are deleted.

**Comment by mstarke** [comment]
As far as I know SSDs are  the reason srm was removed. SSDs tend to be more complicated regarding actual storage than spinning discs. If you overwrite the file via srm or rm it's not guarantee that this actually overwrites the blocks the data was stored to. So srm had no way of being secure. The data might even be left alone and only marked as deleted and the firmware decides when and if it nulls the memory or just uses another block somewhere else. The solution is to never store the file in the first place as the comment in the pull request correctly states.

**Comment by rdoering** [comment]
I totally agree. The plain-text-data should never be stored.
But to fix the missing srm-command problem I used rm -P.

I will try to find a way to use the preview without using a temp file.

**Comment by rdoering** [comment]
NSURLCache, this seems to be the best solution for me. Instead storing the plain data to a drive we could store them to a memory cache object.

**Comment by mstarke** [comment]
Some notes:

```NSURLCache``` seems to be designed in conjunction with ```NSURLSession```. I'm unsure it's possible to act as a cache without actually being one and further more, the cache is for the application (that is MacPass) but quicklookd is fetching the file preview so we might not get a cache it at all. I'm not sure how the whole architecture works, but it seems very dangerous to be able to act as a system wide URL cache so my guess is that it's just application bound. But I'm eager to see what you come up with.

I personally would first try to look if ```srm```is present. MacPass runs currently on 10.9 and above, that means ```srm```could possible be installed. Simply falling back to ```rm -P``` is easier but I would prefer the other way. Both are not secure on SSDs but on spinning discs ```srm```at least should be reasonably good.

**Pull request merged**
