### PR TITLE
Icons as PDF files

### PR DESCRIPTION
**Pull request by JoannaOlsen**
Hopefully you can use these files ... :)

### CODE REVIEW

**Comment by mstarke** [comment]
Can you add the .ai files as well? It would be nice to have the open format not just the finished PDFs?

**Comment by JoannaOlsen** [comment]
You know, since the files aren't SECURED (I did not save them with password protection) you can open PDF files with Illustrator as easily as any .ai file ... fully editable as well ... no need for the .ai files ... ;)

**Comment by mstarke** [comment]
Errr. I know it sounds like a wise-ass but if you save all the files with editing capabilities (has nothing to do with password protection) they are bloated. Just save the .ai files and stripp every editing capabilities form the pdfs. Illustrator saves the ".ai" content inside the PDF to preserve it's editing capabilities. Can I ask what version of AI you used for the files?

**Comment by mstarke** [comment]
Mh. I just checked, they are quite small so it might just work this way. But the comment about editing != password protection still stands. I'll merge this asap and try to include the icons. Thanks again! This is a huge contribution!

**Comment by JoannaOlsen** [comment]
Editing capabilities has nothing to do with being bloated ... it is just how PDF's are ... editable ...

**Comment by mstarke** [comment]
Mh. As far as I understand it, Illustrator stores the complete .ai file inside the pdf and thereby can re-read it. This might create bigger files. PDFs aren't editable in an was way, at least by design. But that's just my rust knowledge. Might have changed over time.

**Comment by JoannaOlsen** [comment]
You can open any PDF file in Illustrator regardless of how it was saved ... except if it was password protected ... then you need the password to edit it ... just like you can open it in Photoshop as well ... though then it will be converted to pixels ...

**Comment by mstarke** [comment]
I did not say that .ai isn't able to interpret the paths. PDFs with vectors can be parsed. But you loose a lot of capabilities compared to the original file. Just a simple example: Create a compound path, save it with and without editing capabilities. If you load both files, you see the one without editing capabilities will just be the result (the compound path expanded), the other file will still have the single parts of the compound path and the operation. Both are editable, but the PDF is ... well ... stripped :)

**Comment by mstarke** [comment]
I'm sorry if I did not make myself clear enough. You're right about the editing but I was referring to the complete .ai file and structure, not just the visible parts. Thats another nice example. Just hide a path. If you save the pdf and reopen it, the path is gone (as it was hidden, and hence not included in the pdf) if you open the pdf saved with editing capabilities the hidden path is still there.

**Comment by JoannaOlsen** [comment]
Well, it would not help you to get the Illustrator files, because I have removed the excess points, paths etc. so the paths should be single layer compund paths ready to use for what ever you choose, like cut out for T-shirt print or what ever ... though I think PDF puts a clipping path on as default ;)

Just curious ... why do you want the icons saved as PDF in the first place ... I mean, why can't you use .ai files directly? ... how about .eps ... or .svg ... is it the programming language that can't handle other formats or something? ... O.o

**Comment by mstarke** [comment]
Cocoa can render images supplied in grayscale (or b/w) in a template fashion. That way you get effects like emboss, highlighting, shadows for free. That's why I chose the b/w approach. PDF is the simplest way I know of to supply vector formats for Cocoa. There's no native method to load SVG files.

Simple answer - easy to load as vectors in Cocoa :)

**Pull request merged**
