### PR TITLE
KeePassHttp support

### PR DESCRIPTION
**Pull request by jameshurst**
I've been using this and no one else has reported any problems, so I guess this is ready for a pull request.

### CODE REVIEW

**Comment by rfilmyer** [comment]
@jamesrhurst James, would you remind rebasing again so I can try this with 0.5.1?

**Comment by jamesrhurst** [comment]
I actually just rebased against master yesterday so it should have everything in 0.5.1.

**Comment by rfilmyer** [comment]
That explains it, I haven't checked since yesterday :p

**Comment by rfilmyer** [comment]
@jamesrhurst I'm having trouble building your fork on 10.10. I loaded the 10.8 SDK, but it fails building at [this line](https://github.com/mstarke/HNHUi/blob/21b97144b2e8272c372584b06c02209f0ca1c2de/HNHBadgedTextFieldCell.m#L92) in the HNHUi submodule.

**Comment by jamesrhurst** [comment]
I'm building using the 10.10 SDK, maybe that's the issue? Also are your submodules up to date?

**Comment by rfilmyer** [comment]
Never mind, I checked out your fork's master instead of the `KeyPassHTTP`branch.
Now everything builds fine.

**Comment by Mirocow** [comment]
why you not merge this pullrequest?

**Comment by mstarke** [comment]
The reason is given in https://github.com/mstarke/MacPass/pull/247#issuecomment-66488491

**Comment by sheavner** [comment]
@jamesrhurst I've been using the http integration for a week or so with chrome latest on Yosemite 10.10.3 and no problems so far.   I do have a feature request tho - to be able to ignore some folders.   I've migrated over from KeePassX v0.43 or something that was pretty old and am still using KP1 files because they work everywhere I need them to work.   KPX and maybe some of my other tools save off every modification to a Backups group and there are multiple copies of each entry.   I'd like to be able to configure it to ignore the Backups folder.

@mstarke It would also be nice if it didn't prompt me everytime I save to KP1 that I'm losing information.  Am I really known to be losing information at this point or does it just say that with every save?

**Comment by rfilmyer** [comment]
Also as an update, I've been using keepasshttp for 2 months without problems. Next step is going to be trying to use it through an nginx proxy.

**Comment by mstarke** [comment]
@sheavner the prompt is based on all the information currently available in the database. I might have to change the the algorithm as I did not touch it for a while. But one thing that's a possible cause is auto type definitions. KP1 does support them via notes and I did not have the time to write an export function that tries to write all KPX auto type information into the KP1 container. But good call as I did not spent too much time refining this feature.

**Comment by dipson** [comment]
@jamesrhurst Thanks for your work on this! Working great so far.

**Comment by shaded2** [comment]
can someone post or send me a build for testing?

**Comment by rfilmyer** [comment]
@shaded2
We're all using [jamesrhurst's keepasshttp fork](https://github.com/jamesrhurst/MacPass/tree/keepasshttp). I think we've been all building it with xcode, but (iirc) I should be able to just send you my built binary.

**Comment by sana128** [comment]
can someone give me  detailed instructions to compile that fork? its giving me so many errors (but work) when I try to compile. Im a noob and dont really understand what im doing.

**Comment by tristan-k** [comment]
I'm also struggling with compiling jamesrhurst's keepasshttp fork. I don't even know if I'm building the keepasshttp branch because I can only download the master. Please advise me.

**Comment by rfilmyer** [comment]
Sure.

Just to confirm, after cloning the repository, you're not able to `git checkout keepasshttp` to switch over to the right branch of James Hurst's fork?

**Comment by rfilmyer** [comment]
And if I'm not mistaken, this should work for you guys. It's the app built from the latest commits.

I just zipped it up, so I'm not sure if anything will break. It's been reliable for me so far.

https://www.dropbox.com/s/2g0y62k9nvw4g6x/MacPass.zip?dl=0

**Comment by shaded2** [comment]
Thanks for the zip @rfilmyer. seems to be working well so far. I can finally unpin keepassx from my dock!

**Comment by tristan-k** [comment]
Thanks @rfilmyer. In the end I succeeded in building it.

**Comment by Floppy** [comment]
Using @rfilmyer's build with PassIFox, and it seems to work perfectly. Good job :D

**Comment by jaimeagudo** [comment]
Thanks @rfilmyer it works just fine for me with chromeIpass on Chrome 45.0.2435.0 canary (64-bit) Mac OS 10.10.3  :boom:  :+1:

**Comment by max-b** [comment]
Built the @jameshurst keepasshttp fork with xcode 4 for yosemite and working fine for me with chromeipass.

Does require a bit of tinkering with xcode build settings. I think the default in the repo is to build for 10.8. @shaded2 if you're still interested in walking through the build process we could set up some out of band chat.

**Comment by nazriel** [comment]
Works very well with 
https://github.com/mmichaa/passafari.safariextension/releases/tag/v1.0.beta2

@jameshurst great job :)

@mstarke maybe there's a way to introduce better workflow so pull requests like this one, which works fine won't rot?

Now I just hope that Safari extension will mature enough, because at the moment it is rather limited compared to the ones for Chromium/Firefox :)

**Comment by mstarke** [comment]
Better workflow: Yup.
The main problem right now is lack of time on my side. This results in a very strange state for the project. There are still a lot of places that lack a lot of polish and functionality and those need to be addressed if any of the "bigger" stuff gets done (namely your suggestion for a plugin system)

**Comment by mstarke** [comment]
Oh. Before I forget - the main reason for this lingering state is the 10.9 target. MacPass in all it's current releases works on 10.8 so including this fork break that and I didn't want to spent time back-porting to 10.8 and just finish some other stuff and then up to 10.9 for the whole project as a minimum requirement.

**Comment by nazriel** [comment]
@mstarke I perfectly understand you, lack of the time is also a big issue for me.

Although I had no idea about 10.8 breakage with this PR so I'm sorry for my ignorance in this regard.
I must admit that I'm fairly new to OSX/iOS world as a user and programmer.

Anyways, cheers up and keep up good work, MacPass is already great at this stage :+1:

**Comment by mstarke** [comment]
No worries :). I'm the one not getting shit done at the moment so I'm the last person to point fingers ;-)

**Comment by mstarke** [comment]
@jameshurst should we try to use this as place to define plugin API so we can move the implement into a plugin-bundle? I think this is  a nice way to determine some core functionality a plugin system has to offer.

**Comment by TomK** [comment]
Hey, @mstarke thanks for the good work on MacPass!
I currently use the keepasshttp branch by @jameshurst and thought I'd mention here (since github isses are not enabled on the fork) i've just noticed the about box still references CocoaHTTPServer which i believe you swapped out for something else in your fork.
Thanks again!

**Comment by Floppy** [comment]
Does this PR add this icon? screen shot 2015-07-21 at 17 23 47

As far as I can tell, the icon appears only when KeePassHttp is running. However, there are no options - is necessary to display it (assuming this is where it comes from)?

**Comment by mstarke** [comment]
Take a look here: #331

**Comment by Floppy** [comment]
Oh, thankyou, I hadn't spotted that. Appreciate the pointer :)

**Comment by sir-brickalot** [comment]
Having trouble using the @jameshurst fork:
I am using it in combination with PasslFox and I never get a match. Using the context menu "Fill User & Pass" opens a window to choose from a couple of entries. All those entries appear to be in the 'Recycle Bin' in MacPass. (Sidenote: Emptying the trash needs a 'Save file...' too, to really delete the files.)
I used the binary from @rfilmyer because I didn't manage to compile from source.

System: 10.10.3 (OSX86)

Any idea?

**Comment by Floppy** [comment]
@sir-brickalot normally when it does that for me, it's because the URL isn't set in the keepass database for that key. Do you have those set correctly for the keys you're trying to use?

**Comment by sir-brickalot** [comment]
@Floppy the behaviour is the same not matter if URL is present or not. Strange is that as long as there are entries in the trash, EVERY entry will be shown as a n option. They don't have to have any correlation to the actual website.
Just tested again with just one key in the trash and fields get actually filled even if it has no similarity to the site. Not the same behaviour on every site. Sometimes I get the "No login found."-warning.

Reproduceable:
- create a fake key with random content and place it in the trash (only one item in trash!)
- open https://my.asos.com/signin and choose "Fill User & Pass"

(sorry for the stupid domain ;) )

**Comment by robbie-c** [comment]
Can I help with this at all? Tried to compile https://github.com/jameshurst/MacPass/tree/keepasshttp and got a build error. Here is exactly what I did:
git clone https://github.com/jameshurst/MacPass.git
cd MacPass/
git checkout keepasshttp
git submodule init
git submodule update
open MacPass.xcodeproj/

Then when I build it fails with the following error:
/Users/MyName/Projects/MacPass/KeePassKit/Core/KPKEntry.m:618:21: Property 'key' not found on object of type 'KPKBinary *'

I'm on OS X Yosemite 10.10.5, Xcode 7.0.1

Happy to help out e.g. if you can't reproduce this yourselves. Also in general, this is a really awesome project and I'm grateful for all the work that must have gone into it!

**Comment by sebastianrothe** [comment]
KPKBinary has the following properties only, data and name. I think the property should be name, not key.

**Comment by jameshurst** [comment]
I took a look at this issue and it appears to be an issue with the version of KeePassKit that we have checked out. The issue in KeePassKit got fixed in https://github.com/mstarke/KeePassKit/commit/ab34319973f38d84f26e5e2fdbfb4bd314fa0779, but because of the API changes made in https://github.com/mstarke/KeePassKit/commit/25b5fd840b526846f442ffa1b1ca0caa5d933e02 I can't update the KeePassKit dependency to the latest verison. The problem with https://github.com/mstarke/KeePassKit/commit/25b5fd840b526846f442ffa1b1ca0caa5d933e02 was that it removed public support for adding/moving an entry to a group at a specified index which is required to support reordering entries. @mstarke is there another way to reorder the entries or should that API be made public again?

**Comment by mstarke** [comment]
@jameshurst To make KeePassKit a framework I started pulling private API into separate headers and in that I also tried to reduce the public API. My initial goal was to use a better parent/child structure but that didn't turn out so nicely. Anyway. The index on an entry was useless from my point of view since entries get sorted all the time, but I guess matching goes through them in the order they are stored inside the array and so order does count there. It's no problem to make the API public again, but I found only one usage to move the configuration entry in [MPDocumentQueryService.m#L85](https://github.com/jameshurst/MacPass/blob/keepasshttp/MacPass/MPDocumentQueryService.m#L85) which should also work with a simple ````- (void) moveToGroup:(KPKGroup*)group;````

**Comment by jameshurst** [comment]
@mstarke When building MacPass with the master branch of KeePassKit the issues that I'm seeing are [MPOutlineDataSource.m#L163](https://github.com/mstarke/MacPass/blob/master/MacPass/MPOutlineDataSource.m#L163) and [MPOutlineDataSource.m#L168](https://github.com/mstarke/MacPass/blob/master/MacPass/MPOutlineDataSource.m#L168) which both require the `atIndex` parameter.

Checking right now, it looks like the `index` parameter of `NSOutlineViewDataSource` returns `-1` for any drop that I do, so perhaps `- (void)moveToGroup:(KPKGroup *)group` would suffice there.

**Comment by mstarke** [comment]
@jameshurst Ah, didn't take a look at MacPass since I'm ahead locally with my trail (and error) run to get editing to work in a better fashion. That's the reason I did not push anything using the current KeePassKit code for MacPass yet. Sorry for any inconveniences this is causing!

**Comment by flinz** [comment]
@jameshurst I finally got around to trying the keepasshttp branch, but unfortunately i can not get it to work so far. I am on OSX 10.11.1 and built with Xcode 7.1.

- neither [passafari.safariextension](https://github.com/mmichaa/passafari.safariextension) nor [passifox](https://github.com/pfn/passifox/) seem to connect at all
- [chromeipass](https://chrome.google.com/webstore/detail/chromeipass/ompiailgknfdndiefoaoiligalphfdae) at least shows me that I am running the ``KeePassHttp-ObjC`` server. However, it  
[does not find any connected databases](https://cloud.githubusercontent.com/assets/97735/11088499/ff33d93a-8862-11e5-84f9-39a6363a2c0f.png).

The KeepassHttp server seems to be started ([i can see the icon](https://cloud.githubusercontent.com/assets/97735/11088355/eda60b94-8861-11e5-8293-5b63e5e295c4.png)), however clicking the icon does not open any dropdown - don't know whether this is intended behavior.

To build it i had to circumvent the [KeePassKit issue](https://github.com/mstarke/MacPass/issues/378) by changing ``binary.key --> binary.name`` which let me build (got this [from the issue](https://github.com/mstarke/MacPass/issues/378#issuecomment-152447557)). Might it be that this breaks something?

**Comment by rodneyrod** [comment]
I'm building it for 10.10 with XCode 7.1 too, I had an error with the KPKEntry.m file too, but editing as per above enabled it to build.

However, the option to enable the KeepassHttp server is greyed out and there seems to be no way to enable it.

Also, is integration with KeeFox being worked on?

**Comment by mstarke** [comment]
KeeFox uses KeePassRPC so this requires a port of KeePassRPC. I'm a bit bewildered why there isn't a common approach and everyone that creates a browser plugin tries to built a new solution. Anyway. Not my time to argue ;).

Also a side note. I've created a very raw but sort of working plugin system for MacPass and did a dirty port of KeePassHTTP over to it and it seems to be working.

**Comment by mstarke** [comment]
Im closing this for now since I did port the fork to a plugin [MacPassHTTP](https://github.com/MacPass/MacPassHTTP) . There seems to be a bug in the plugin so it's not working correctly. But when fixed it should run.

Beware that the current master is a mess. I need to clean it up but I wanted to push all the changes out.

**Pull request closed without merging**
